services:
  minio:
    image: minio/minio:latest 
    container_name: dotocr-minio
    command: server /data --console-address ":9003"  
    environment:
      - MINIO_ROOT_USER=minioadmin 
      - MINIO_ROOT_PASSWORD=minioadmin  
    ports:
      - "9002:9000" 
      - "9003:9003"  
    volumes:
      - minio-data:/data 
    restart: unless-stopped 

volumes:
  minio-data: 
